apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbase-assignment
spec:
  selector:
    matchLabels:
      app: backbase-assignment
  replicas: 1
  template:
    metadata:
      labels:
        app: backbase-assignment
    spec:
      containers:
        - name: backbase-assignment
          image: backbase-assignment:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: backbase-assignment
  labels:
    run: backbase-assignment
spec:
  selector:
    app: backbase-assignment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backbase-assignment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backbase-assignment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50