flyway:
  errorOverrides: 1000:1262:D
  schemas: movies_info
  url: ${DB_HOST}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always

omdb:
  url: http://www.omdbapi.com
  token: ${OMDB_TOKEN}