flyway:
  errorOverrides: 1000:1262:D

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies_info?allowLoadLocalInfile=true
    username: user
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always