db:
  url: jdbc:mysql://localhost:3306/movies_info?allowLoadLocalInfile=true

spring:
  datasource:
    url: ${db.url}
    username: user
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: movies_info
    url: ${db.url}
    user: root
    password: mysql

server:
  error:
    include-message: always

omdb:
  url: http://www.omdbapi.com
  token: <apiKey>