spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: ${DB_HOST}
    user: ${DB_ROOT_USER}
    password: ${DB_PASSWORD}

omdb:
  token: ${OMDB_TOKEN}